### ISSUE TITLE
New-PSSession connection to Exchange Online fails due to deprecated auth method (LP04 Lab4 Ex3)

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#156]
- Learning Path 4 - Lab 4 - Exercise 3 - Create message encryption rules
- Task 2 – Create a Mail Flow Encryption Rule using Windows PowerShell
- Steps 4 - 14

The PowerShell command at step 13 of the above-referenced task (quoted and linked below) fails with a message indicating an "Access is denied" response from Exchange Online.

```
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic -AllowRedirection
```

https://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security/blob/7ab41932e208ff2fc351662a3de8432dc1e5200f/Instructions/Labs/LAB_AK_04_Lab4_Ex3_Message_Encryption.md?plain=1#LL87C2-L87C2

The below-linked Microsoft documentation page states that this authentication method is no longer supported.

https://learn.microsoft.com/en-US/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps#appendix-comparison-of-old-and-new-connection-methods

As a workaround, in our lab environment, we were able to authenticate by skipping steps 4 - 14 of the task and substituting the below command, as suggested by content of the above link. Note that we are not making any claims about the necessity of PowerShell module installation or other preceding setup steps relative to other lab environments.

```
Connect-ExchangeOnline -UserPrincipalName Holly@<Your Tenant Name>.onmicrosoft.com
```

Following authentication via the above command, we were able to successfully run the command at step 15 and confirm that the corresponding rule was created.

Thank you for taking a look at this issue. Please reply with any requests for additional info that you may have.

**Comment by tfrink** [comment]
Thank you for bringing this to our attention. Another user contacted us about this same issue, but interestingly, their workaround was to assign the Exchange Administrator role to Holly Dickson. However, since as you mentioned, that authentication method is being deprecated, we updated the instructions to follow your recommendation. We have the user install and connect to the Exchange Online PowerShell module (ExchangeOnlineManagement) and then run the following command:

New-TransportRule -Name "Encrypt rule for Guest Services" -SentTo "[Gservices@adatum.com](mailto:Gservices@adatum.com)" -SentToScope "NotinOrganization" -ApplyRightsProtectionTemplate Encrypt

Originally, we ran the command as it was, with the ApplyOME property. While this worked, PowerShell returned a message indicating the ApplyOME property was being deprecated in favor of the ApplyRightsProtectionTemplate property. With this property, we assigned it the Encrypt template, which is the default encryption template. 

Thank you so very much for bringing this to our attention. We really appreciate you for helping us get this issue fixed.
