### ISSUE TITLE
Module 3 - Lab3 Exercises 1 and 2

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security#23]
# Module: 00
#### Step: 00

Description of issue

Attack simulator v1 has been retired so this lab is not usable at all. Please remove or rewrite to use Attack Simulator v2

Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
Hi Ed, Thank you for your catch I will be addressing this issue shortly. I will push a change early in March.

**Comment by edbakermct** [comment]
Any update on this I am teaching it again this next week?

**Comment by geschwei** [comment]
HI Ed, Im currently testing this lab right now for updates. I will be removing the brute force exercise and password spray at the moment due to not having the ability to use those services. I am in the process of rebuilding exercise 2 in order fill the gap.

**Comment by geschwei** [comment]
I have update LAB 3 Exercise 1 to reflect the current Attack simulation training.

**Comment by edbakermct** [comment]
Thanks George much obliged JIT lab work ....

Sent from iOS Outlook<https://aka.ms/qtex0l> protected by Microsoft Enterprise Mobility and Security
________________________________

**Comment by geschwei** [comment]
Hi Ed, I have updated Lab 3 Exercise 1. Exercise 2 Is still in the process of rework. Since brute force attacks and password spray are not in V2 of the Attack simulation yet. I

**Comment by WigF1** [comment]
Hey George, 

I know you said you updated Lab 3, Exercise 1, however, there is no 'Email and collaboration' present on the left menu at all if you follow the lab steps.

In Lab 2, you have people click the Security Admin center which takes them to https://protection.office.com and which you refer to in the labs correctly as 'Office 365 Security and Compliance Center'.

In Lab 3, Exercise 1, Task 1, Step 2 you say "Select the tab containing the Microsoft 365 Security center" - they have no tab open from any prior instruction with this. 

In order to be able to see the 'Email and Collaboration', or to be in the MS Security center, students would need to manually browse to https://security.microsoft.com.

Can you update the instructions accordingly?

**Comment by geschwei** [comment]
Hi WigF1, I will look into what you have caught and update accordingly.

**Comment by MikeVeschi** [comment]
Notice this has not been updated or cleared yet here is more input

Module 3 - Lab 3 - Exercise 1 

Task 1:

Step 4  Under Simulation Coverage to the Right. Click Launch simulation for non-simulated users.
Review the ( 5 ) Types

Step 5 Proceed to enable MFA for Holly.


Task 2: 

Under the Credentials Harvest section, select View Details., Review Details and click X
Then Click Next

Step 4 Review the ( 5 ) Types

Eliminate Steps 5 and 6

On Step 7 use name, ignore UI
In Description there is a typo on against

Step 11 Hit Next Twice

Task 3:

Step 12 As Holly in Attack Simulation Training, Click Refresh and Under Overview click the Phishing Test as Type Credential Harvest

Review the Payloads and Improvement Actions

**Comment by geschwei** [comment]
this issue has been resolved with the updated lab guide.
